---
title: "Coursera: Getting and Cleaning Data Capstone Project"
author: "Nipunjeet Gujral"
output: 
  html_document:
  theme: flatly
  highlight: haddock
---



```{r Libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
```


```{r define and combine test and train data sets, message=FALSE, warning=FALSE}
train_set <- data.table::fread(file = "C:/Users/nipun/Downloads/UCI HAR Dataset/train/X_train.txt", 
                      sep = " ", header = FALSE)
test_set <- data.table::fread(file = "C:/Users/nipun/Downloads/UCI HAR Dataset/test/X_test.txt", 
                              sep = " ", header = FALSE)
combined_data <- dplyr::bind_rows(list(train_set, test_set))
```


```{r measure the mean and sd per column, message=FALSE, warning=FALSE}
mean_per_column <- base::apply(combined_data, 2, mean)
sd_per_column <- base::apply(combined_data, 2, sd)
```


```{r creat tidy df with mean and sd per measurment}
temp1 <- cbind(mean_per_column, sd_per_column) 
descriptive_data <- temp1 %>% 
  dplyr::as_tibble() %>% 
  dplyr::mutate(Variable = row.names(temp1))

```


